---
  - name: 패키지 설치 - {{ package }}
    yum:
      name: "{{ package }}"
      state: latest

  - name: 서비스 기동 - {{ service }}
    service:
      name: "{{ item }}"
      enabled: yes
      state: started
    loop: "{{ service }}"