---
# 파일 배포
# (ansible) custom.fact -- 배포 --> (web1) /etc/ansible/facts.d/custom.fact
- name: 사용자 정의 팩트 파일 배포하기
  hosts: webserver
  gather_facts: no
  tasks:
  - name: 사용자 정의 팩트 파일 배포
    file:
      path: /etc/ansible/facts.d
      state: directory
      recurse: yes
      mode: '0755'
  - name: 파일 배포 하기
    copy:
      src: custom.fact 
      dest: /etc/ansible/facts.d/custom.fact