---
- name: 웹 패키지 설치 - httpd, mod_ssl
  yum:
    name: "{{ pkg_web }}"
    state: latest

- name: 웹 서비스 기동 - httpd
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items: "{{ svc_web }}"

- name: 웹 서버 설정 - 가상 호스트 설정
  template:
    src: vhost.conf.j2
    dest: /etc/httpd/conf.d/vhost.conf
  notify: restart httpd

- name: 웹 디렉토리 생성 - /var/www/vhosts/{{ ansible_hostname }}
  file:
    path: /var/www/vhosts/{{ ansible_hostname }}
    state: directory

- name: 웹 서버 설정 - /var/www/vhosts//{{ ansible_hostname }}/index.html 파일 설정
  template:
    src: index.html.j2
    dest: "/var/www/vhosts/{{ ansible_hostname }}/index.html"

- name: 방화벽에 서비스 등록 - http, https
  firewalld:
    service: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  with_items: "{{ fw_svc }}"