---
- name: 새로운 사용자 추가
  hosts: web2.example.com
  become: true
  remote_user: ansible
  vars_files:
    - secret2.yml
  tasks:
  - name: 사용자 추가 및 암호 설정
    user:
      name: "{{ username }}"
      password: "{{ pwhash|password_hash('sha512') }}"