---
# 1) 방화벽 서비스 OFF - http , https , mysql => firewalld
# 2) 서비스 disabled - httpd , mariadb => service
# 3) 서비스 디렉토리 삭제 - /var/www/html => file
# 4) 패키지 삭제 - ... => yum
- name: "DB 웹서버 설정 복원 작업"
  hosts: webservers
  gather_facts: no
  tasks:
    # 4) 패키지 삭제 - httpd
    - name: "패키지 삭제 - httpd"
      yum:
        name:
        - httpd
        - mod_ssl
        - php
        - php-mysqlnd
        - php-pdo
        - mariadb-server
        - mariadb
        - python3-pip
        state: absent
  # 3) 서버 디렉토리 삭제
    - name: "파일 삭제 - /var/www/html/index.html"
      file: 
        path: /var/www/html/index.html
        state: absent
  # 2) 서비스 disabled - httpd , mariadb => service
    - name: 서비스 disabled - httpd , mariadb => service
      service:
        name: "{{ item }}"
        state: stopped
        enabled: no
      loop:
      - httpd
      - mariadb
  # 1) 방화벽 서비스 OFF - http , https , mysql => firewalld
    - name: 방화벽 서비스 OFF - http , https , mysql
      firewalld:
        service: "{{ item }}"
        state: disabled
        permanent: yes
        immediate: yes
      loop:
      - http
      - https
      - mysql